apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appTwo.name }}
  namespace: {{ .Values.appTwo.namespace }}
  labels:
    app: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: {{ .Values.appTwo.image }}
        imagePullPolicy: Always
        nodeSelector:
          application: product
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: ingress working!!!
