apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appOne.name }}
  namespace: {{ .Values.appOne.namespace }}
  labels:
    app: nginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.appOne.image }}
        imagePullPolicy: Always
        nodeSelector:
          application: product
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "50m"
